### ISSUE TITLE
The link to "Pa11y Dashboard" in readme.md is broken

### ISSUE THREAD

**Issue by jtechera** [pa11y/pa11y-webservice#106]
Hi,
The link to "Pa11y Dashboard" in the readme.md points to:
[https://github.com/pa11y/pa11y-webservice/blob/master/pa11y-dashboard](https://github.com/pa11y/pa11y-webservice/blob/master/pa11y-dashboard)

I can send a PR with the fix if that's ok.
Thanks.

**Comment by josebolos** [comment]
Fixed in Version 3.2.0.
