### ISSUE TITLE
Error connecting to MongoDB

### ISSUE THREAD

**Issue by mgifford** [pa11y/pa11y-webservice#119]
I don't think this is related to https://github.com/pa11y/pa11y-webservice/issues/115 but just wanted to link the two. Not sure why this isn't working for me. 

```
$ PORT=8080 npm start

(node:26780) ExperimentalWarning: The fs.promises API is experimental

> pa11y-webservice@3.2.0 start
> node index.js

Error connecting to MongoDB:
{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"}

Pa11y Webservice started
mode:     undefined
uri:      http://0.0.0.0:8080
database: mongodb://localhost/pa11y-webservice
cron:     false

Error starting Pa11y Webservice:
failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
```

**Comment by owebudde** [comment]
@mgifford, 

It's in the requirements. Looks like you'll have to create a db.

> Pa11y Webservice also requires a MongoDB database to be available so it can store the results of the tests. The database doesn't have to be in the same server or computer where Pa11y Webservice is running from.

**Comment by grelas** [comment]
What version of MongoDB should we be using to connect? v3?

**Comment by mgifford** [comment]
Would it be good to add an optional line in the set up to say:

Check if Mongodb is installed:
  `npm list mongoose`

If it isn't, then install it with:
  `npm install mongodb`

**Comment by danyalaytekin** [comment]
Hi both, thanks for asking about this @mgifford and for your help @owebudde. There are a few different ways to set up and manage MongoDB itself - I'm not sure where `mongoose` would arise here, but perhaps we were using it back in 2021! I've tried to make it slightly clearer [in the readme](https://github.com/pa11y/pa11y-webservice/commit/59bf0f9021a3cbb42c409f71381a96becf2b77c5?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) that an instance is expected to be up and running as a prerequisite.
