### ISSUE TITLE
[EPIC] Release Pa11y-webservice v5

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y-webservice#140]
These are the tasks still missing for next release of `pa11y-webservice`:

* Drop support for Node v12 (which will become unsupported in late April).
* Add support for Node v16, and potentially v18 (which will be released in April) if the MongoDB driver adds support for it.
* The MongoDB driver has already been upgraded from v3 to v4.4.1 on the [`next` branch](https://github.com/pa11y/pa11y-webservice/tree/next) but I don't think this version of the MongoDB driver supports Node 16 already.

We should probably wait until late April / early May to see if the mongodb peeps release a 4.5 or 5.0 update for their driver in the meantime and, if not, drop support for Node 12 and release v5 of webservice anyway, as adding support for new versions of Node is not a breaking change but removing support for old versions is.

**Comment by danyalaytekin** [comment]
An [IPV6 fix later](https://github.com/pa11y/pa11y-webservice/pull/149) and `mongodb@3` _appears_ to be working well with Node 18 and 20, although we'll have to do some thorough regression testing.  As you touched on in #113, upgrading to `mongodb@4` (or 5 or 6) would require significant refactoring owing to our use of the library `async` to manage our callback-oriented approach, which those versions no longer support.  As discussed, I'll close this for now but will continue to track work for `pa11y-webservice@5` in [milestone 5.0](https://github.com/pa11y/pa11y-webservice/milestone/2).
