### ISSUE TITLE
Question: can I call Pa11y API directly

### ISSUE THREAD

**Issue by hibaAkroush** [pa11y/pa11y-webservice#143]
Hello 

I have been trying to generate accessibility reports by writing a node script, pa11y is catching many errors for my pages and I'm trying to incorporate it by getting the errors in json form. 
the problem is that using the webservice is a lot of boilerplate for me I need to install it on machines of every person who will generate the report and have to start the server each time I want to generate data

I am trying to get accessibility data for public pages using pa11y, for lighthouse I have been using this API endpoint [Page Speed insight](https://developers.google.com/speed/docs/insights/v5/get-started) with ACCESSIBILITY category 

the question is there a similar API for pa11y?

**Comment by josebolos** [comment]
Hi @hibaAkroush,

Thank you for creating this issue. Unfortunately I'm not aware of any free or paid-for public APIs that provide this information.
