### ISSUE TITLE
Update for pa11y 5.x

### ISSUE THREAD

**Issue by xtfer** [pa11y/pa11y-webservice#56]
Just wondering if there are any plans to update this for pa11y 5.x?

**Comment by rowanmanning** [comment]
Hi xtfer, it's quite unlikely webservice will get this update as we're focusing more on Sidekick development and it'd be a fair amount of work to make the switch. If somebody else was interested in doing this and testing it then we would accept a PR, just don't want to dedicate lots of core team time

**Comment by xtfer** [comment]
No problem. Thanks for updating.
