### ISSUE TITLE
Fix npm audit issues

### ISSUE THREAD

**Issue by msilvagarcia** [pa11y/pa11y-webservice#65]
Currently, there are 61 security issues with the dependencies of pa11y-webservice. `npm audit` provides partial solutions to those. My approach is:
- `npm install hapi@^16.7.0`
- `npm install joi@^14.3.0`
- `npm install --save-dev mocha@5.2.0`

The problem with this is that mocha freezes after tests run. They explain why in these patch notes (https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit) and I could make it stop running by appending the mocha command with `--exit`, but that would require a pull request to https://github.com/rowanmanning/makefiles/blob/master/Makefile.node

So, can you guide me on the best way to fix this?

Cheers!

**Comment by josebolos** [comment]
Fixed as part of [version 3.0.0](https://github.com/pa11y/pa11y-webservice/blob/master/CHANGELOG.md#300-2019-07-04).
