### ISSUE TITLE
Upgrade dependencies and migrate when needed

### ISSUE THREAD

**Issue by paazmaya** [pa11y/pa11y-webservice#69]
Relating to #68, would be great to have all dependencies up to date and release a new version with minimum Node.js version 8, to match `pa11y`.

I would be happy to work on this via PRs, but since there are some many open PRs, not sure if there is anyone willing to review and merge...

@rowanmanning possible?

**Comment by joeyciechanowicz** [comment]
#68 is now merged. We're getting there! We are planning a release shortly with all the recently merged PRs

**Comment by josebolos** [comment]
Fixed as part of [version 3.0.0](https://github.com/pa11y/pa11y-webservice/blob/master/CHANGELOG.md#300-2019-07-04).
