### ISSUE TITLE
Update required Node dependency in README

### ISSUE THREAD

**Issue by joeyciechanowicz** [pa11y/pa11y-webservice#71]
#58 bumped the Pa11y version to 5 and as a result the minimum node version is now 8.
The README needs updating with this, and the section regarding PhantomJS rewritten.

**Comment by josebolos** [comment]
Fixed as part of [version 3.0.0](https://github.com/pa11y/pa11y-webservice/blob/master/CHANGELOG.md#300-2019-07-04).
