### ISSUE TITLE
Upgrade mongodb client to v3

### ISSUE THREAD

**Issue by joeyciechanowicz** [pa11y/pa11y-webservice#78]
If we want to upgrade MongoDB to v3 then we will have to have a think as it makes a change that the DB is not selected by default. One has to manually select the database using `.db(name)`.
This means we will have to add a section to the configuration to pass this in, which will be a breaking change.

**Comment by josebolos** [comment]
I've just realised that webservice is already using version 3.x of the mongodb driver so maybe this is not needed any more?
