### ISSUE TITLE
Problems with certain ssl-configurations?

### ISSUE THREAD

**Issue by benboit** [pa11y/pa11y-webservice#92]
Hello,

since a few weeks my setup pa11y dashboard running version 3.0.0 is not able to test my setup pages anymore. Error message on console is:

`xxx.pa11y | Starting to run one-off task @ Wed Sep 11 2019 08:38:10 GMT+0000 (UTC)
xxx.pa11y | Starting task 5d78ad119c5abb0700e8107f
xxx.pa11y |   > PhantomJS page created
xxx.pa11y |   > Opening "https://shop.xxx.com/de-de/" in PhantomJS
xxx.pa11y |   > PhantomJS page closed
xxx.pa11y |   > PhantomJS browser exited
xxx.pa11y | Failed to finish task 5d78ad119c5abb0700e8107f: Error opening url "https://shop.xxx.com/de-de/" : Operation canceled
xxx.pa11y | Finished running one-off task @ Wed Sep 11 2019 08:38:10 GMT+0000 (UTC)`

The website im testing is reachable from the host-machine. The hoster recently changed the ssl cert in use and also disabled old versions of tls.

An upgrade to the most up to date version of the dashboard didnt help:

`Starting to run one-off task @ Wed Sep 11 2019 17:20:39 GMT+0200 (GMT+02:00)
Starting task 5d78ef8642e1ed0007aeb842
  > Running Pa11y on URL https://shop.xxx.com/de-de
  > Launching Headless Chrome
  > Opening URL in Headless Chrome
  > Injecting HTML CodeSniffer
  > Injecting Pa11y
  > Running Pa11y on the page
model:task:runById failed, with id: 5d78ef8642e1ed0007aeb842
Evaluation failed: [object Object]
Failed to finish task 5d78ef8642e1ed0007aeb842`

Im not sure if this is an issue with the dashboard or the webservice. Currently pa11y is running in a self build docker-container. Running it directly on the host-machine, even with newer node versions doesnt help.

Any clue?

**Comment by josebolos** [comment]
Version 4 of Pa11y Dashboard and Pa11y Webservice use puppeteer instead of phantomjs, so compatibility with sites should have very much improved.

Feel free to reopen the issue if you're still experiencing problems.
